### ISSUE TITLE
Windows 7 implementation won't list the serial USB related serial ports.

### ISSUE THREAD

**Issue by LucaWolf** [euantorano/serial.nim#26] opened 2019-10-04 10:52 UTC
For some reason the ``SetupDiGetClassDevs`` with ``GUID_DEVINTERFACE_COMPORT`` approach won't list the ports created by the sys serial Usb driver (mostly used by embedded devices). Tested on Win7, both pro and home editions.

Opening (once the com name is known) and data transfer works fine.

If you have serial USB devices to test with, could you please confirm it works for you?

Thanks,
Luca

**Comment by euantorano** [comment] 2019-10-04 11:04
I’ve got some FTDI based USB serial adapters which I originally tested with. 

When I wrote the original code there were 3 or 4 different recommended ways to get all devices. I think the .net framework looks in the registry for instance I’ll maybe try that approach and see if it makes a difference.

**Comment by wirebiter** [comment] 2019-11-01 06:58
I can confirm this behaviour on windows 7 here. I have a few different USB-RS232 converters and they are listed. The Arduino COM port for example is not. 

The screenshot attached shows the arduino connected on COM33 and a USB-RS232 connected to COM34.

![image](https://user-images.githubusercontent.com/2179912/68007861-3dd52080-fc7d-11e9-8d2d-c1cd46abad4d.png)

**Comment by euantorano** [comment] 2019-11-01 07:07
Interesting, thanks for the update. I’ll see what I can do, there are definitely some other ways to list them such as registry scanning.

**Comment by mp035** [comment] 2019-11-27 02:42
I have a custom CDC based USB product which is detected fine on Windows 10,  but as part of that project, I've implemented Registry scanning to find the details of my USB devices.  Would you like me to provide a gist?  Or pehaps a pull request?  For a pull request though, I'd need some specifics of the devices which are not currently detected to do some testing.

**Comment by euantorano** [comment] 2019-11-27 07:06
A pull request would be appreciated. I’ve tested the following devices which all work:

- Physical serial port
- FTDI bases RS232/485 usb serial adapter 
- Moxa NPort Ethernet serial adapter
- B&B electronics Ethernet serial adapter

**Comment by mp035** [comment] 2019-12-08 01:21
@LucaWolf , @wirebiter , I have created a branch off of my fork named "registry_scan", you can get it here:[https://github.com/mp035/serial.nim/tree/registry_scan]( https://github.com/mp035/serial.nim/tree/registry_scan).  Be sure to checkout the correct branch (NOT master) after you clone.

Can you please test it and check if it solves your issue, if it works I will ask @euantorano to check the implementation is acceptable.

**Comment by mp035** [comment] 2019-12-08 01:36
@LucaWolf , @wirebiter I just realised I made an error, be sure to checkout commit 3c6ff3847f41e3535fed05c6f529c38feefdcef0 or later from branch registry_scan (pushed only a few minutes ago).

**Comment by LucaWolf** [comment] 2019-12-10 12:40
@mp035. Thanks, all listed fine now via your changes. I could only test on Win7. If you're happy there are no side-effects on Win10 (like duplicates for example) then please feel free to send a pull request to the original author.

@euantorano, TBH this is low priority for me and probably it only used to fail on Win7. Could close the issue if wanting.

**Comment by euantorano** [comment] 2019-12-10 12:54
I’ll leave this open since it sounds like we have a working patch available. Once we get that merged, I’ll push a new version and will look at the Linux issue at a later date (I need a Linux machine with Bluetooth to test with).

**Comment by mp035** [comment] 2019-12-10 14:59
The registry scanning is a fairly simple implementation that I have successfully used in my own projects for many years from WinXP through to Win10, so I doubt there'd be any problems.  I've tested on Win 10 with devices that are recognised through both processes, and there are no duplicates.  I'll submit a pull request for euantorano to review.

**Comment by mp035** [comment] 2019-12-10 21:33
@LucaWolf , @euantorano  has made a good suggestion on how to simplify the scanning code.  Could you please do me a BIG favour and check if your Arduino serial port (and any other problematic devices) is listed in the registry keys at HKLM\HARDWARE\DEVICEMAP\SERIALCOMM on Win7?

**Comment by LucaWolf** [comment] 2019-12-11 08:00
Yes, the device is there. I vaguely recall seeing other implementation(s) scanning that registry so I believe is a good approach.

**Closed** 2019-12-12 15:03 UTC
